// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80NqLwbQ6s1vOiM9TQvEYfOubohXhC6k',
    appId: '1:942152496560:web:303bc758a77771375cd275',
    messagingSenderId: '942152496560',
    projectId: 'blocfirebase-edecf',
    authDomain: 'blocfirebase-edecf.firebaseapp.com',
    storageBucket: 'blocfirebase-edecf.appspot.com',
    measurementId: 'G-ZFYQ9PGJRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbXaTtplbsO2CrvPYxW3HLZBDttx0avw',
    appId: '1:942152496560:android:53a360ef0e0429cd5cd275',
    messagingSenderId: '942152496560',
    projectId: 'blocfirebase-edecf',
    storageBucket: 'blocfirebase-edecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6aHPO1tEfo2my6xi5q2TpQa-WoB90I0',
    appId: '1:942152496560:ios:8391c5281e8dfc2f5cd275',
    messagingSenderId: '942152496560',
    projectId: 'blocfirebase-edecf',
    storageBucket: 'blocfirebase-edecf.appspot.com',
    iosBundleId: 'com.example.blocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6aHPO1tEfo2my6xi5q2TpQa-WoB90I0',
    appId: '1:942152496560:ios:64860b64fdf7198d5cd275',
    messagingSenderId: '942152496560',
    projectId: 'blocfirebase-edecf',
    storageBucket: 'blocfirebase-edecf.appspot.com',
    iosBundleId: 'com.example.blocFirebase.RunnerTests',
  );
}
